server:
  port: 8004
spring:
  rabbitmq:
    host: gutsandgun.kro.kr
    port: 11005
    username: gutsandgun
    password: gutsandgun
  writedb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://gutsandgun.kro.kr:12006/sending?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: gutsandgun
    hikari:
      maximum-pool-size: 10
  readdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://gutsandgun.kro.kr:12010/read?usessl=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: gutsandgun
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true
        show-sql: true
        generate-ddl: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://gutsandgun.kro.kr:10006/realms/KITe/protocol/openid-connect/certs

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace  # query의 ?에 어떤 값이 들어가는지 TRACE Log에 값을 보여줌


keycloak:
  realm: KITe
  bearer-only: true
  ssl-required: external
  resource: spring_auth
  auth-server-url: https://gutsandgun.kro.kr:10006
  credentials:
    secret: rxxJSm63zgPqob8ShKv4t3GyAu0wrUXo


rabbitmq:
  queue1:
    name: SKT
    exchange: SKT-exchange
  queue2:
    name: KT
    exchange: KT-exchange
  queue3:
    name: LG
    exchange: LG-exchange
  routing:
    key:
      queue1: SKT
      queue2: KT
      queue3: LG

